### ISSUE TITLE
Trouble to configure 

### ISSUE THREAD

**Issue by Lediak** [oqyh/cs2-Kill-Sound#1]
Hello, 

I dont know how to configure the sound, did i have to put these {
  // you can test any sound path ingame console type "play <soundpath>"
  // Sound Path will in  https://github.com/oqyh/cs2-Kill-Sound/blob/main/sounds/sounds.txt
  //TO DISABLE MAKE IT "" empty
  "HeadShotSound": "sounds/training/bell_normal.vsnd_c"
}
![image](https://github.com/oqyh/cs2-Kill-Sound/assets/156964948/34cf4f1b-b7e5-4307-922b-ea6589cd8e84)
Can u tel me ? Thanks !

**Comment by oqyh** [comment]
hello Lediak,

download full zip at
https://github.com/oqyh/cs2-Kill-Sound/releases/tag/1.0.0

then drop Kill_Sound in plugins folder
`csgo/addons/counterstrikesharp/plugins/`

after restart server

it will auto create config at configs/plugins folder will be `Kill_Sound `
`csgo/addons/counterstrikesharp/configs/plugins`

**Comment by Lediak** [comment]
Thx a loooooot !!! Its my first serveur and i didnt knew the config folder !

**Comment by oqyh** [comment]
np

**Comment by Lediak** [comment]
I'm sorry to bother you again. Can you explain to me how I connect a database to my csssharp plugins? Thanks in advance !!

**Comment by oqyh** [comment]
hi Lediak,
join counterstrikesharp discord we will help you
https://github.com/roflmuffin/CounterStrikeSharp?tab=readme-ov-file#counterstrikesharp
