### ISSUE TITLE
Add a custom song

### ISSUE THREAD

**Issue by Lediak** [oqyh/cs2-Kill-Sound#2]
Did you know if its possible to add a custum sound ? I want to add de HEEEAADSHOOOT and Multikill Rampage etc...

**Comment by oqyh** [comment]
> Did you know if its possible to add a custum sound ? I want to add de HEEEAADSHOOOT and Multikill Rampage etc...

yes we can but sadly at this moment no,
we dont have sv_downloadurl yet, to let players download server custom sounds
