### ISSUE TITLE
Request: play diferent sounds on diferent number of kills

### ISSUE THREAD

**Issue by dandzhiel** [oqyh/cs2-Kill-Sound#5]
Can you add an option to play diferend sounds on multikills?
Example: 
if a player makes 2 kills without dieing, play sound "sounds/example/example1.vsnd_c"
If a player makes 3 kills without dieing, play sound "sounds/example/example2.vsnd_c"
etc.
sound paths would be configurable, same as number of kills to play the sound
There is already a rank plugin which tracks number of kills and displays it as number of "double kills, triple kills, godlikes" etc, so I guess it should be possible.

If you make this, it will be possible to add quake sounds.
If you will work on this, I can provide workshop item with quake sounds and test it on my server, if you are interested

**Comment by oqyh** [comment]
> Can you add an option to play diferend sounds on multikills? Example: if a player makes 2 kills without dieing, play sound "sounds/example/example1.vsnd_c" If a player makes 3 kills without dieing, play sound "sounds/example/example2.vsnd_c" etc. sound paths would be configurable, same as number of kills to play the sound There is already a rank plugin which tracks number of kills and displays it as number of "double kills, triple kills, godlikes" etc, so I guess it should be possible.
> 
> If you make this, it will be possible to add quake sounds. If you will work on this, I can provide workshop item with quake sounds and test it on my server, if you are interested

Done Download 1.0.5

https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/releases/tag/1.0.5
