### ISSUE TITLE
How to install dependencies

### ISSUE THREAD

**Issue by ToHold** [oqyh/cs2-Kill-Sound#6]
Hello,

I'm new to cs2 hosting, I installed MetaMod, CSSharp and SimpleAdmin, I can't find a way to install Newtonsoft.Json and MySqlConnector. Any tips ? By the way I host on my own debian server.

**Comment by oqyh** [comment]
> Hello,
> 
> I'm new to cs2 hosting, I installed MetaMod, CSSharp and SimpleAdmin, I can't find a way to install Newtonsoft.Json and MySqlConnector. Any tips ? By the way I host on my own debian server.

its in zip Kill-Sound-GoldKingZ.1.1.1.zip

![2024-06-01 20_46_17-Kill-Sound-GoldKingZ 1 1 1_3 zip](https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/assets/48490385/f8eaa832-010d-4855-8df2-0a3bbc8d4805)


Or Download Manually


![2024-06-01 20_46_54-oqyh_cs2-Kill-Sound-GoldKingZ_ Kill Sound HeadShot BodyShot Quake Dink](https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/assets/48490385/b5db4ff4-59b0-4cfe-967d-65518f51ecc5)

**Comment by ToHold** [comment]
So just copying the addons folder in csgo should install them ?
Well I thought it was the reason I got this interface :

![20240601185043_1](https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/assets/38291374/2af87114-ee85-43ab-ba5a-2efe34296ba4)

Now I have no idea, any idea ?

**Comment by ToHold** [comment]
I also installed MultiAddonManager mm_extra_addons 3230015783 works well. It asked me to download addon on first connection, but no sound is played even if I set to true the KS_EnableQuakeSounds property.

**Comment by oqyh** [comment]
> So just copying the addons folder in csgo should install them ? Well I thought it was the reason I got this interface :
> 
> ![20240601185043_1](https://private-user-images.githubusercontent.com/38291374/335815685-2af87114-ee85-43ab-ba5a-2efe34296ba4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjA5OTksIm5iZiI6MTcxNzI2MDY5OSwicGF0aCI6Ii8zODI5MTM3NC8zMzU4MTU2ODUtMmFmODcxMTQtZWU4NS00M2FiLWJhNWEtMmVmZTM0Mjk2YmE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE2NTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OTllYTcyZTJiMWFiNzgzMjI1NTYzZmU5MmI2NmU0NWI1NzRjOWZkY2I3YjNkMjAyNWMyNzJiZWVhYzc0NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u1Pm-dh8MrkQ1Uu5jGink9_emP74gvI7oRY_vATfFjk)
> 
> Now I have no idea, any idea ?

this means you missing lang

follow these steps:
-------------------------
1- Go to  File "..\addons\counterstrikesharp\configs\ `core.json` " And Open It 
2- Check What Server Lang Using example     "ServerLanguage": " `en` "
3- Go to  Folder `"..\addons\counterstrikesharp\plugins\Kill-Sound-GoldKingZ\lang"` And Make Sure same "`en` .json"

**Comment by ToHold** [comment]
Oh ok I understand, I didn't noticed that this counterstrikesharp ServerLanguage property was linked to yours. Thanks I'll give a try.

**Comment by ToHold** [comment]
Thanks ! It was it !
You are super reactive I Love it !!

![20240601191421_1](https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/assets/38291374/af6c6d49-38e1-4d4c-a607-e55a9d5daa77)

But still have no sounds, any idea ? I remember that I had muted a workshop map sounds in console, but I can't remember the command could it be the reason ?

**Comment by oqyh** [comment]
> Thanks ! It was it ! You are super reactive I Love it !!
> 
> ![20240601191421_1](https://private-user-images.githubusercontent.com/38291374/335817018-af6c6d49-38e1-4d4c-a607-e55a9d5daa77.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjI1MjYsIm5iZiI6MTcxNzI2MjIyNiwicGF0aCI6Ii8zODI5MTM3NC8zMzU4MTcwMTgtYWY2YzZkNDktMzhlMS00ZDRjLWE2MDctZTU1YTlkNWRhYTc3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE3MTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMGMwMDA2NGE0NDAxYTlkMjAzYzE1ZWQ5NjhjNTYzMjNkYzE3ZTJmYWI2M2M2YjVhYmE1NmUwM2QwOTA1ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a8eAQyOJoqlR9goArT68mYYK7dug8x5Xav53T-JeVY4)
> 
> But still have no sounds, any idea ? I remember that I had muted a workshop map sounds in console, but I can't remember the command could it be the reason ?

for sounds 
follow these steps:
-------------------------

1- Check  MultiAddonManager Is Mount To Addons 3230015783 To check it works type in game console "play sounds/GoldKingZ/Quake/megakill.vsnd_c" if sound plays means you good if not means MultiAddonManager Is Not Mounted Or You Set snd_toolvolume  Lower Set In game Console "snd_toolvolume 1"

2- Enable KS_EnableQuakeSounds

3- Open Menu In Game And Make Sure Quake Is Set To `On`

**Comment by ToHold** [comment]
1 - I re prompt mm_extra_addons 3230015783 here is the result :
```
[MultiAddonManager] Refreshing addons (3230015783)
[MultiAddonManager] Adding search path: /home/cs2/server/game/bin/linuxsteamrt64/steamapps/workshop/content/730/3230015783/3230015783.vpk
```
Seems ok to me

I also set snd_toolvolume 1 in client console and try play sounds/GoldKingZ/Quake/megakill.vsnd_c but nothing is played. Is there somewhere on client's pc I should check to ensure files are downloaded ?

2 - Here is my config file : 
![image](https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/assets/38291374/4566407e-e215-4a38-a95e-320aea16dab1)

3 - Here is config in game : 
![image](https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/assets/38291374/d3bdcedd-869b-423f-ad76-e4a99c11d5fb)

**Comment by oqyh** [comment]
> ...

> [!NOTE]
> Keep In Mind Doing "snd_toolvolume 1" while you in the server and reconnect will result set to what it was (ask valve why)                                                                                                                              
> what you do is setup your "snd_toolvolume 1"  while you in main menu where you see your character so they value will not change then join server


After That Follow These Steps Even If You Did It
------------------------------------------------------

1- Download Last Release [[Metamod](https://www.sourcemm.net/downloads.php/?branch=master)] 

Make Sure (2.x)

![2024-06-02 00_07_18-NVIDIA GeForce Overlay DT](https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/assets/48490385/b9d4b380-6ae3-490c-962c-2f808dfcbaac)

Download  Depend Your Machine 

![2024-06-02 00_07_34-NVIDIA GeForce Overlay DT](https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/assets/48490385/8b6dcc12-b0e1-4375-abeb-f82763dc7d85)




2- Download Last Release [[MultiAddonManager](https://github.com/Source2ZE/MultiAddonManager/releases)] 

Download  Depend Your Machine 

![2024-06-02 00_13_14-NVIDIA GeForce Overlay DT](https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/assets/48490385/340eb93e-cc92-4348-8e3e-ed8b5ea7b61a)

3- Go to File "D:\Local_Host\CS2\game\csgo\cfg\multiaddonmanager\ `multiaddonmanager.cfg` " Open It 

Change 
mm_extra_addons 				` "" `
To 
mm_extra_addons 				` "3230015783" ` 

4- Restart Server 

5- Join Server You Should Good To Go

**Comment by ToHold** [comment]
It works ! Was missing step 3- I didn't edit multiaddonmanager.cfg, just mm_extra_addons 3230015783 in console and not in file.
Thanks you !

**Comment by oqyh** [comment]
> It works ! Was missing step 3- I didn't edit multiaddonmanager.cfg, just mm_extra_addons 3230015783 in console and not in file. Thanks you !

glade i help you
