### ISSUE TITLE
Menu is working, but no sounds?

### ISSUE THREAD

**Issue by DigitalFriends** [oqyh/cs2-Kill-Sound#7]
Hey, lovely plugins, thanks for all your work. 

I cant manage to get this working thought, i get the menu to work, it all looks fine. But there are no sounds. 
Maybe i missed something? Can you instruct me or update the instructions on howto? Would also like to use the workshop sounds along with the default sounds.

**Comment by oqyh** [comment]
> Hey, lovely plugins, thanks for all your work.
> 
> I cant manage to get this working thought, i get the menu to work, it all looks fine. But there are no sounds. Maybe i missed something? Can you instruct me or update the instructions on howto? Would also like to use the workshop sounds along with the default sounds.

glad to hear that

yes follow these steps even if you did it

 https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/issues/6#issuecomment-2143571914

**Comment by DigitalFriends** [comment]
Great! Thank you. 

Some other questions, would it be possible to make an option for the quake sounds not to be broadcast to all players? That the players only hear their own sounds?
Also, are we able to set the volume of the sounds manually somehow? I would like to lower the sounds of the bells a bit. 

Damn man, great work on these plugins, i love em. Thank you!

**Comment by oqyh** [comment]
> Great! Thank you.
> 
> Some other questions, would it be possible to make an option for the quake sounds not to be broadcast to all players? That the players only hear their own sounds? Also, are we able to set the volume of the sounds manually somehow? I would like to lower the sounds of the bells a bit.
> 
> Damn man, great work on these plugins, i love em. Thank you!

glade you like it,

sound broadcast, adding per sound "Announcement" true will broadcast to all, set it false will play to player direct without announcement 

sound volume, you cant control it, you can lower orginal mp3 before upload is the best solution via https://mp3cut.net/ set volume -80% and above is best so far

**Comment by DigitalFriends** [comment]
Thank you! 

_sound volume, you cant control it, you can lower orginal mp3 before upload is the best solution via https://mp3cut.net/ set volume -80% and above is best so far_
Where are the audio files located? Can you guide me on how to do this?

**Comment by oqyh** [comment]
> Thank you!
> 
> _sound volume, you cant control it, you can lower orginal mp3 before upload is the best solution via https://mp3cut.net/ set volume -80% and above is best so far_ Where are the audio files located? Can you guide me on how to do this?

you can use mine i made it lower 

sounds/GoldKingZ/Training/bell_normal.vsnd_c
my worshop 3230015783 
and my workshop sounds list you can find it here 
https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/blob/main/sounds/Gold%20KingZ%20WorkShop%20Sounds.txt


or you can use take orginal cs2 sounds by following 
1- find your sound that you want by typing in console while you ingame :

play <soundpath>

cs2 soundpaths you will find it here 

https://github.com/oqyh/cs2-Kill-Sound-GoldKingZ/blob/main/sounds/sounds.txt

example 

play sounds/ambient/de_inferno_children.vsnd_c

2- once you like it download cs2 viewer
https://valveresourceformat.github.io/
 to decompile and take the orginal sound from cs2 then modify it as you like then upload it to your own workshop

**Comment by oqyh** [comment]
> Thank you!
> 
> _sound volume, you cant control it, you can lower orginal mp3 before upload is the best solution via https://mp3cut.net/ set volume -80% and above is best so far_ Where are the audio files located? Can you guide me on how to do this?

you can close this issue once everything ok
