### ISSUE TITLE
Quake sounds stopped playing since todays update

### ISSUE THREAD

**Issue by Magic8Ballin** [oqyh/cs2-Kill-Sound#8]
The Quake sounds were working perfectly in my server yesterday. Now today after the update the sounds stopped working.

I've checked the logs and didn't find any errors.

I don't know what's wrong. I love this plugin! Thanks mister!

**Comment by Magic8Ballin** [comment]
A guy on the Counter-Strike Sharp discord told me its a MultiAddon plugin issue and not related to this plugin.

Thanks for the great stuff man!!! Long live Counter-Strike!!!!

**Comment by Magic8Ballin** [comment]
Oh I also have 2 different quake sound packs that I used to have available to players in my CS:GO server. Players would be able to select from 3 different packs (Quake Sounds, Anime Sounds, Daddy Sounds). I had custom packs made with an Anime girl and some freaky stuff with Daddy sounds.

Might it be possible to allowe the selection of different sound packs?

**Comment by oqyh** [comment]
> Might it be possible to allowe the selection of different sound packs?

will be soon



> The Quake sounds were working perfectly in my server yesterday. Now today after the update the sounds stopped working.

you can check if multiaddons fault or plugin by typing in game console while you in the server

play <soundpath>

if you hear sound, the multiaddons works fine and custom sound downloaded perfect
